//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFPhotos
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DbContextContainer : DbContext
    {
        public DbContextContainer()
            : base("name=DbContextContainer")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Photo>()
                .HasMany<Person>(photo => photo.People)
                .WithMany(person => person.Photos)
                .Map(photoPerson =>
                {
                    photoPerson.MapLeftKey("PersonPhoto_Photo_Id");
                    photoPerson.MapRightKey("PersonPhoto_Person_Id");
                    photoPerson.ToTable("PersonPhoto");
                });
        }
    
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Person> People { get; set; }
    }
}
