//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace DbContext
{
    using System;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    public partial class Comment
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Content { get; set; }
        [DataMember]
        public int PostId { get; set; }
    
        [DataMember]
        public virtual Post Post { get; set; }
    }
}
