//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostComment
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Runtime.Serialization;

    [DataContract(IsReference=true)]
    public partial class Comment
    {
        [DataMember]
        public int CommentId { get; set; }
        [DataMember]
        public string Text { get; set; }
        [DataMember]
        public string PostPostId { get; set; }
        [DataMember]
        public int PostPostId1 { get; set; }
    
        public virtual Post Post { get; set; }

        public bool AddComment()
        {
            using (var ctx = new ModelPostCommentContainer())
            {
                bool bResult = false;
                if (this == null || this.PostPostId1 == 0) return bResult;
                if (this.CommentId == 0)
                {
                    ctx.Entry<Comment>(this).State = EntityState.Added;
                    var p = ctx.Posts.Find(this.PostPostId1);
                    ctx.Entry<Post>(p).State = EntityState.Unchanged;
                    ctx.SaveChanges();
                    bResult = true;
                }
                return bResult;
            }
        }

        public Comment GetCommentById(int id)
        {
            using (var ctx = new ModelPostCommentContainer())
            {
                return ctx.Comments.Find(id);
            }
        }
    }
}
