//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFPhotos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/WCFPhotos", IsReference=true)]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FirstNameField;
        
        private int IdField;
        
        private string LastNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPersonService")]
public interface IPersonService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetById", ReplyAction="http://tempuri.org/IPersonService/GetByIdResponse")]
    WCFPhotos.Person GetById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetById", ReplyAction="http://tempuri.org/IPersonService/GetByIdResponse")]
    System.Threading.Tasks.Task<WCFPhotos.Person> GetByIdAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetAll", ReplyAction="http://tempuri.org/IPersonService/GetAllResponse")]
    WCFPhotos.Person[] GetAll();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetAll", ReplyAction="http://tempuri.org/IPersonService/GetAllResponse")]
    System.Threading.Tasks.Task<WCFPhotos.Person[]> GetAllAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IPersonServiceChannel : IPersonService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PersonServiceClient : System.ServiceModel.ClientBase<IPersonService>, IPersonService
{
    
    public PersonServiceClient()
    {
    }
    
    public PersonServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WCFPhotos.Person GetById(int id)
    {
        return base.Channel.GetById(id);
    }
    
    public System.Threading.Tasks.Task<WCFPhotos.Person> GetByIdAsync(int id)
    {
        return base.Channel.GetByIdAsync(id);
    }
    
    public WCFPhotos.Person[] GetAll()
    {
        return base.Channel.GetAll();
    }
    
    public System.Threading.Tasks.Task<WCFPhotos.Person[]> GetAllAsync()
    {
        return base.Channel.GetAllAsync();
    }
}
